baseURL = "https://abhi.page"
languageCode = "en-us"
title = "abhi.page"
theme = "introduction"
# publishDir = "docs"

disqusshortname = "abhi-page"			# https://gohugo.io/content-management/comments
googleAnalytics = "UA-166494184-1"		# https://gohugo.io/templates/internal/#google-analytics

[taxonomies]
	tag = "tags"
	# category = "categories"
	stack = "stack"


## CONFIGURATIONS FOR 'INTRODUCTION' THEME...
[params]
    themeStyle                   = "dark"				# Choose "light" or "dark"
    favicon                      = "/img/fav.ico"		# Path to favicon file
    showRSSButton                = true					# Show rss button in navigation
    fadeIn                       = true					# Turn on/off the fade-in effect
    fadeInIndex                  = true					# Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    customCSS                    = ["custom.css"]		# Include custom css files placed under assets/
    # email                      = "youremail@email.com"   # E-mail address for contact section

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"		# Input either "medium" or "large" or "fullheight"
        showLatest               = true				# Show latest blog post summary
        showAllPosts             = true			# Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3				# Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true				# Show your current local time in contact section
        timeZone                 = "Asia/Calcutta"	# Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"			# https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false			# Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = false
        pinterest                = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://linkedin.com/in/abhiweb"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
		html_attributes = "title=\"LinkedIn: abhiweb\""
    [[params.social]]
        url   = "https://github.com/manustays"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
		html_attributes = "title=\"Github: manustays\""
    [[params.social]]
        url   = "https://twitter.com/abhiweb"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
		html_attributes = "title=\"Twitter: @abhiweb\""
    [[params.social]]
        url   = "https://in.pinterest.com/manustays/"
        icon  = "pinterest" # icon name without the 'fa-'
        icon_pack = "fab"
		html_attributes = "title=\"Pinterest: manustays\""
    [[params.social]]
        url   = "https://stackoverflow.com/users/505601/abhishek?tab=profile"
        icon  = "stack-overflow" # icon name without the 'fa-'
        icon_pack = "fab"
		html_attributes = "title=\"Stack Overflow\""
    # [[params.social]]
    #    url   = "https://facebook.com/"
    #    icon  = "facebook-f" # icon name without the 'fa-'
    #    icon_pack = "fab"
    # [[params.social]]
    #    url = "mailto:youremail@email.com"  # For a direct email link, use "mailto:test@example.org".
    #    icon = "paper-plane" # icon name without the 'fa-'
    #    icon_pack = "fas"
    # [[params.social]]
    #    url   = "https://mastodon.social/"
    #    icon  = "mastodon" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #    html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification
